family_categories = ["Air Terminals",
                     "Cable Trays",
                     "Casework",
                     "Columns",
                     "Communication Devices",
                     "Conduit Fittings",
                     "Data Devices", "Doors",
                     "Duct Accessories",
                     "Duct Fittings",
                     "Duct Insulations",
                     "Electrical Equipment",
                     "Electrical Fixtures",
                     "Entourage",
                     "Fire Alarm Devices",
                     "Furniture Systems",
                     "Furniture",
                     "Generic Models",
                     "Lighting Devices",
                     "Lighting Fixtures",
                     "Mass",
                     "Mechanical Equipment",
                     "Nurse Call Devices",
                     "Parking",
                     "Pipe Accessories",
                     "Pipe Fittings",
                     "Planting",
                     "Plumbing Fixtures",
                     "Railings",
                     "Security Devices",
                     "Site",
                     "Specialty Equipment",
                     "Sprinklers",
                     "Structural Columns",
                     "Structural Connections",
                     "Structural Foundations",
                     "Structural Framing",
                     "Structural Stiffeners",
                     "Telephone Devices",
                     "Windows"]
# print family_categories